// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider satisfies various provider interfaces.
var _ provider.Provider = (*ArenamlProvider)(nil)
var _ provider.ProviderWithEphemeralResources = (*ArenamlProvider)(nil)

type ArenamlProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// ArenamlProviderModel describes the provider data model.
type ArenamlProviderModel struct {
	ServerURL types.String `tfsdk:"server_url"`
}

func (p *ArenamlProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "arena"
	resp.Version = p.version
}

func (p *ArenamlProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				Description: `Server URL`,
				Required:    true,
			},
		},
	}
}

func (p *ArenamlProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data ArenamlProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		resp.Diagnostics.AddError("server_url is required", "The server_url attribute must be provided in the provider configuration.")
		return
	}

	cl, err := NewClient(ServerURL)
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error creating arenaml client: %s", err))
		return
	}

	resp.DataSourceData = cl
	resp.ResourceData = cl
}

func (p *ArenamlProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewEngineResource,
		NewBasisResource,
		NewInputResource,
		NewStepResource,
		NewOutputResource,
		NewPipelineDagResource,
		NewPipelineResource,
		NewOrgResource,
		NewTeamResource,
		NewUserResource,
		NewStoreResource,
		NewSensorResource,
		NewSensorProfileResource,
		NewDroneResource,
		NewDroneProfileResource,
	}
}

func (p *ArenamlProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewEngineDataSource,
		NewBasisDatasource,
		NewInputDatasource,
		NewStepDatasource,
		NewOutputDatasource,
		NewPipelineDatasource,
		NewOrgDatasource,
		NewTeamDatasource,
		NewUserDatasource,
		NewStoreDatasource,
		NewSensorDataSource,
		NewSensorProfileDataSource,
		NewDroneDataSource,
		NewDroneProfileDataSource,
	}
}

func (p *ArenamlProvider) EphemeralResources(ctx context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &ArenamlProvider{
			version: version,
		}
	}
}
